openapi: 3.0.0
info:
  title: Financial Broker App API
  description: |
    This is the backend API for the **Financial Broker App**, a platform where users can invest a chosen amount and receive a fixed return — similar to mutual funds, but with a predefined percentage yield.

    **Key Features:**
    - Users can create an account, deposit an investment amount, and track returns.
    - Fixed ROI plans (e.g., 24% annual returns) with transparent payout schedules.
    - Portfolio tracking, withdrawal requests, and reinvestment options.
    - Admin panel to manage users, investments, and payout operations.

    **Example Use Case:**
    1. User invests ₹50,000.
    2. System locks the investment under a fixed return plan (e.g., 24% p.a.).
    3. Monthly or quarterly payouts are automatically credited to the user.

    **Useful Links:**
    - [Backend Repository](https://github.com/razrahul/CMS_Backend)
    - [Frontend UI (Netlify)](https://contact-fromdata.netlify.app)
    - [Frontend UI (Render)](https://client-frontend-juzp.onrender.com)

  termsOfService: http://swagger.io/terms/

  contact:
    name: Rahul Kumar
    email: razrahuleee@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: https://dashboard-backend-06ls.onrender.com/api/v1
    description: stgae Server
  - url: http://localhost:5000/api/v1
    description: Local Server

components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: auth
  - name: role
  - name: Dummy
  - name: plan
  - name: Testing
  - name: Account
  - name: Lead
  - name: Notification
  - name: Ticket
  - name: Transaction
paths:
  /auth/request-otp:
    post:
      tags:
        - auth
      summary: request otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phone: '9708712422'
                email: rahulkumar852145@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/verify-otp:
    post:
      tags:
        - auth
      summary: verify-otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phone: '9708712422'
                phoneOtp: '903542'
                email: rahulkumar852145@gmail.com
                emailOtp: '228205'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login-request-otp:
    post:
      tags:
        - auth
      summary: login request otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phoneoremail: rahulkumar852145@gmail.com
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: 'verify otp and login '
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phoneoremail: rahulkumar852145@gmail.com
                otp: '174981'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /role:
    post:
      tags:
        - role
      summary: create Role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                roleName: SuperAdmin
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - role
      summary: get All Roles
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /role/{uuId}:
    get:
      tags:
        - role
      summary: get role by id
      parameters:
        - name: uuId
          in: path
          schema:
            type: string
          required: true
          example: eaa3b4fc-cf10-4632-bdb1-b1e2a89d91c5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - role
      summary: update role
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                roleName: rahul
      parameters:
        - name: uuId
          in: path
          schema:
            type: string
          required: true
          example: eaa3b4fc-cf10-4632-bdb1-b1e2a89d91c5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - role
      summary: delete role
      parameters:
        - name: uuId
          in: path
          schema:
            type: string
          required: true
          example: eaa3b4fc-cf10-4632-bdb1-b1e2a89d91c5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/dummy-entry/{id}:
    post:
      tags:
        - Dummy
      summary: user_dummy_entry
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: Niranjan
                lastName: Patel
                roleId: a8065dc7-95f8-429b-9204-67b75fd2d8fd
                pan: DAJDG4150P
                creditScore: '650'
                currentBalance: '1000'
                address: Nepal
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '2'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/dummy-user/{id}:
    get:
      tags:
        - Dummy
      summary: find dummy_user
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/pan-verification/{id}:
    post:
      tags:
        - Dummy
      summary: Dummy Pan verification
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: >-
                "{\r\n   \"pan\":\"SDBHHED2545\",\r\n  
                \"dob\":\"21-205-25\"\r\n}"
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /plan:
    post:
      tags:
        - plan
      summary: create plan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                planName: Sigma 2.O
                planTitle: Sigma Invesment || Mega auction
                planDescription: Invest here content return 12%
                minimumInvestment: '500'
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - plan
      summary: get All Plan
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /plan/{uuId}:
    get:
      tags:
        - plan
      summary: get Plan by id
      security:
        - noauthAuth: []
      parameters:
        - name: uuId
          in: path
          schema:
            type: string
          required: true
          example: 115e423a-fc62-4929-b1ec-fb0fb8fac0b9
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - plan
      summary: update Plan by id
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                planName: Sigma 2.O
                planTitle: Sigma Invesment || Mega auction
                planDescription: Invest here content return 12%
                minimumInvestment: '500'
      security:
        - noauthAuth: []
      parameters:
        - name: uuId
          in: path
          schema:
            type: string
          required: true
          example: 115e423a-fc62-4929-b1ec-fb0fb8fac0b9
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - plan
      summary: delete Plan by id
      security:
        - noauthAuth: []
      parameters:
        - name: uuId
          in: path
          schema:
            type: string
          required: true
          example: 115e423a-fc62-4929-b1ec-fb0fb8fac0b9
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /auth/plans:
    post:
      tags:
        - Testing
      summary: create userPlan
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                memberId: Rk001
                planId: c3410fe1-c5e3-42ff-b754-0c221c9c8c70
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /account:
    post:
      tags:
        - Account
      summary: Craete Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                accountHolderName: RAhul Kumar
                accountNumber: '97087124225869'
                IFSCCode: SBIN0003532
                bankName: STATE BANK OF INDIA
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /account/{memberId}:
    get:
      tags:
        - Account
      summary: get Account by memberId --Only for Admin
      security:
        - bearerAuth: []
      parameters:
        - name: memberId
          in: path
          schema:
            type: string
          required: true
          example: RK001
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /account/member:
    delete:
      tags:
        - Account
      summary: Delete Account member
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lead:
    post:
      tags:
        - Lead
      summary: create Lead
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: 'Rahul '
                lastName: Kumar
                number: '9708712422'
                email: raz@gmail.com
                title: 'Add This contant '
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Lead
      summary: get All Leads
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lead/search:
    get:
      tags:
        - Lead
      summary: Search All Leads
      parameters:
        - name: emailornum
          in: query
          schema:
            type: string
          example: raz
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /lead/{emailornum}:
    get:
      tags:
        - Lead
      summary: get Lead by email and number
      parameters:
        - name: emailornum
          in: path
          schema:
            type: integer
          required: true
          example: '9808712422'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /notif/member:
    get:
      tags:
        - Notification
      summary: Get Notification member --> Self
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Notification
      summary: delete notification by  memeber --> self
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /notif:
    post:
      tags:
        - Notification
      summary: create Notification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                notificationType: E-commerce
                notificationTitle: This check foe notifiication create
                notificationMessage: you can check for there Link for E-commerce
                memberId: RK001
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Notification
      summary: get Alll Notification
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /notif/{id}:
    get:
      tags:
        - Notification
      summary: get notification by UUid
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: d28d1794-acf7-4d3e-b9e2-4214ea2c41fd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Notification
      summary: update notification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                notificationType: E-commerce
                notificationTitle: This check for update   notifiication create
                notificationMessage: you can check for there Link for E-commerce
                memberId: RK001
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: d28d1794-acf7-4d3e-b9e2-4214ea2c41fd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Notification
      summary: delete notifiication by uuid
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: d28d1794-acf7-4d3e-b9e2-4214ea2c41fd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /ticket:
    post:
      tags:
        - Ticket
      summary: create ticket
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                ticketSubject: This is test for ticket
                priority: priority to test
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Ticket
      summary: get all ticket
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /ticket/{id}:
    post:
      tags:
        - Ticket
      summary: ticket assign to user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                userId: d43affc1-7c2a-42be-8e5a-6f9159a92506
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 992a7cd2-dbc5-4e5b-b0cc-87a83eaa0820
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Ticket
      summary: get ticket by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 992a7cd2-dbc5-4e5b-b0cc-87a83eaa0820
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Ticket
      summary: update ticket
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                ticketSubject: This is test for update ticket
                priority: priority to test
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 992a7cd2-dbc5-4e5b-b0cc-87a83eaa0820
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Ticket
      summary: delete ticket
      security:
        - noauthAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          example: 992a7cd2-dbc5-4e5b-b0cc-87a83eaa0820
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trans/create-order:
    post:
      tags:
        - Transaction
      summary: Create order(Transaction)
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trans/verify-payment":
    post:
      tags:
        - Transaction
      summary: Verify transaction
      requestBody:
        content: {}
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /trans/razorpay-key:
    get:
      tags:
        - Transaction
      summary: get razorpay key
      security:
        - noauthAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}